require('./balanceOf.js');
require('./totalSupply.js');
require('./allowance.js');
require('./approve.js');
require('./transferFrom.js');
require('./transfer.js');
require('./transferOwnership.js');
require('./burn.js');
require('./mint.js');